Add instruction for setup
OneSock-inc/OnlyOne pull request #58
Opened 2022-09-02 09:07 UTC by jorisSchaller

This PR add a README.md file in the backend folder explaining how to build and configure the backend

2022-09-02 09:48 UTC, Luhrel requested changes

2022-09-02 09:48 UTC, Luhrel commented on backend/README.md
> +The DB module is where all the grpc calls are made to the database. We don't do grpc call ourself we only use the grpc client offered by the firestore lib. The matching algorithmes is implemented the
```suggestion
The DB module is where all the [gRPC](https://grpc.io/) calls are made to the database. We don't do gRPC call ourself as we only use the gRPC client offered by the firestore library. The matching algorithms is implemented there. We also take care of the error handling there. For example, if the data sent by a user to a route / response handler is ill formed or simply missing, we detect it there before creating a database record . 
```

2022-09-04 09:44 UTC, Luhrel requested changes

2022-09-04 09:44 UTC, Luhrel commented on backend/README.md
> +The DB module is where all the [grpc](https://grpc.io) calls are made to the database. We don't do grpc call ourself, inestead we use the firestore library that do the grpcs call itself. The matching
```suggestion
The DB module is where all the [grpc](https://grpc.io) calls are made to the database. We don't call any grpc ourself, instead we use the firestore library (which calls the grpcs). The matching algorithm is implemented there. We also take care of the error handling there, for example, if the data send by a user to a route / response handler is ill formed or simply missing we detect it there before creating saving it to the database. 
```
- The sentence `The matching algorithm is implemented there` is not obvious: where ?
- Why do we speak about grpc ?

2022-09-05 14:47 UTC, jorisSchaller reviewed
Rewording

2022-09-06 07:43 UTC, Luhrel requested changes

2022-09-06 07:43 UTC, Luhrel commented on backend/README.md
> +The DB module is where all the calls to the database are made. We use the firestore [library](https://pkg.go.dev/google.golang.org/cloud/firestore) . The matching algorithm is implemented in this mod
```suggestion
The DB module is where all the calls to the database are made. We use the firestore [library](https://pkg.go.dev/google.golang.org/cloud/firestore). The matching algorithm is also implemented in this module, and it is currently a [knn](https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm) search in a [kdtree](https://github.com/sjwhitworth/golearn/blob/master/kdtree/kdtree.go). We also take care of the error handling related to the database there, for example if the data sent by a user to a route / response handler is ill formed or simply missing, we detect it there before saving it to the database. 
```

2022-09-06 07:50 UTC, Luhrel approved these changes

2022-09-06 07:50 UTC, merged